
/**
 * This file was generated by langFragBuilder() from source file: 001_en.lang.php
 */
const lang_entry en_lang_entry[] = {
	ADD_LE("start.group", "This command can only be used in private."),
	ADD_LE("start.private", "Send /help to show the command list."),
};
