
/**
 * This file was generated by langFragBuilder() from source file: id.lang.php
 */
const lang_entry id_lang_entry[] = {
	ADD_LE("start.group", "Command ini hanya dapat digunakan di private message."),
	ADD_LE("start.private", "Kirim /help untuk menampilkan daftar perintah."),
};
